### ISSUE TITLE
Object.create() occasionally returns results out of order

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/sails-postgresql#128]
Let's say I do

```javascript
Users.create([{
    'email': 'kev@inburke.com',
    'password': 'hunter2'
}, {
    'email': 'foo@example.com',
    'password': 'foobar'
}]).then(function(users) {
    users[0].email.should.equal "kev@inburke.com";
});
```

Occasionally we would see this assertion fail. Running Postgres in a VM, on a small dataset. 

Is this behavior expected? If it is, maybe it should be documented?

**Comment by kevinburke** [comment]
I've managed to isolate the issue here, https://circleci.com/gh/kevinburke/sails-postgresql/13 just run the tests until you get a failure.

**Comment by kevinburke** [comment]
(Running on circleci because that was the environment I initially found the failure in. Probably reproducible on Travis as well).

**Comment by particlebanana** [comment]
A quick fix would be to change https://github.com/balderdashy/sails-postgresql/blob/master/lib/adapter.js#L417 to `.eachSeries` but we should make it use a single query. I'll have some time early next week to dive in and get some fixes out.

**Comment by tjwebb** [comment]
`.eachSeries` will slow things down, though, since each create will then be done sequentially. Should the order really matter, here?

**Comment by kevinburke** [comment]
This was unexpected behavior for three reasons:

- it'll return in order for, maybe, 29 out of 30 queries, and then return one out of order. This makes it easy for people to assume that the queries are returned in order, as they might not see this issue locally/in testing.

- there's a symmetry between creating a list of items and then immediately using the returned values, at least in the code.

```javascript
Users.create([{
    'email': 'kev@inburke.com',
    'password': '12345'
}, {
    'email': 'foo@example.com',
    'password': 'averymuchstrongerpassword'
}]).then(function(users) {
    var weakPasswordUser = users[0]; // or whatever
});
```

- I would hope that the records are inserted into the DB in the same order that they're passed to the create() function.

- the documentation for `create()` mentions nothing about ordering being guaranteed, or not guaranteed.

**Comment by tjwebb** [comment]
Do other adapters behave the same way? If you depend on insertion order, you can use `Promise.all` and pass it a list of `User.create`. I'm just having trouble seeing the general case for forcing sequential insertion.

**Comment by kevinburke** [comment]
I added a test to the waterline suite in a PR, if you can merge it you can
probably check.

On Friday, January 2, 2015, Travis Webb <notifications@github.com> wrote:

> Do other adapters behave the same way? If you depend on insertion order,
> you can use Promise.all and pass it a list of User.create. I'm just
> having trouble seeing the general case for forcing sequential insertion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-68579210>
> .
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by kevinburkeshyp** [comment]
Any update here?

**Comment by tjwebb** [comment]
I'm still not convinced that it's worth it to reduce performance for all list insertions to accommodate this use case. If you want to access the first object, you can just `var users = [ ... ]` before the create statements.

**Comment by kevinburkeshyp** [comment]
maybe I'm crazy, but how do Promise.all() and Promise.join() manage to do
multiple things all at once and still return them in order? we are waiting
until all of the items are completed before returning the results, right?

On Tue, Mar 10, 2015 at 12:45 PM, Travis Webb <notifications@github.com>
wrote:

> I'm still not convinced that it's worth it to reduce performance for all
> list insertions to accommodate this use case. If you want to access the
> first object, you can just var users = [ ... ] before the create
> statements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-78132738>
> .
>



-- 
kevin

**Comment by devinivy** [comment]
Status of this?  I do know that waterline merged PR https://github.com/balderdashy/waterline/pull/795 which changes the waterline fallback for `createEach` to insert sequentially.

**Comment by kevinburke** [comment]
I haven't had a chance to reproduce, we are still on the old version. 300
runs should be enough to produce the issue on the old code, if you can
reproduce it on the old code and then run the new code and don't see it
after 300 batch inserts then it's probably fixed.

On Wednesday, April 15, 2015, devin ivy <notifications@github.com> wrote:

> Status of this? I do know that waterline merged PR
> balderdashy/waterline#795
> <https://github.com/balderdashy/waterline/pull/795> which changes the
> waterline fallback for createEach to insert sequentially.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-93614940>
> .
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by dmarcelino** [comment]
I believe balderdashy/waterline-adapter-tests#27 tests this and I ran the tests and none of the official adapters breaks the new test: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/59863844#L1785 (the current broken tests are the known ones). So I believe this is fixed.

Having said that I agree with what @tjwebb said on https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-78132738. Using `asyncSeries` will slow down queries and for some people it will be needlessly. We should be able to make this behaviour optional...

**Comment by kevinburkeshyp** [comment]
would `async.map` help? from [the docs](https://github.com/caolan/async#maparr-iterator-callback):

> Note, that since this function applies the iterator to each item in parallel, there is no guarantee that the iterator functions will complete in order. However, the results array will be in the same order as the original arr.

**Comment by dmarcelino** [comment]
@kevinburkeshyp, I think you're onto something. That would satisfy the requirement of returning `.create()` results in the order of insertion without limiting the performance.

**Comment by dmarcelino** [comment]
Given balderdashy/waterline-adapter-tests#58 has been merged and sails-postgresql passes the test created by @kevinburke it's now safe to close this. Please reopen if you are still experiencing this.
