### ISSUE TITLE
Upgrade waterline-sequel dependency

### ISSUE THREAD

**Issue by devinivy** [balderdashy/sails-postgresql#151]
For upgrade instructions from 0.1 to 0.3 see,
https://github.com/balderdashy/waterline-sequel/commit/0c0b857656d4111048d4084fa66711a02ccf2afc#commitcomment-10748559
https://github.com/balderdashy/waterline-sequel/commit/bcce0ed9c7790eb2b47b468d9bc26c4cdea2270d#commitcomment-10748553

Soon, possibly upgrade to Knex or equivalent.

**Comment by dmarcelino** [comment]
Relates to #147. :wink:

**Comment by dmarcelino** [comment]
As stated in https://github.com/balderdashy/sails-postgresql/pull/147#issuecomment-94052761, updating the dependency has broken the sails-postgres build.

**Comment by dmarcelino** [comment]
Created balderdashy/waterline-sequel#39 to address this.

**Comment by dmarcelino** [comment]
#39 is fixed so once waterline-sequel `0.3.1` is released sails-postgresql build will pass all tests.

**Comment by dmarcelino** [comment]
waterline-sequel 0.3.1 has been released and now sails-postgresql build passes all tests.
