### ISSUE TITLE
Processor clobbers Buffers

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/sails-postgresql#194]
If you try creating a `'binary'` data type and passing a Buffer as the value, node-postgres returns a Buffer object, but the call to `_.cloneDeep(values)` converts a Buffer into a weird looking object. You can see that in this script: https://gist.github.com/kevinburkeshyp/c45a344a15e040ec6f0e.

I'm not sure how to use that new Buffer object in a meaningful way. Maybe the Buffer should be converted to a string before calling `_.cloneDeep` on it. 

Here's a possible patch:

```javascript
Processor.prototype.cast = function(table, values) {

  var self = this;
  for (var key in values) {
    if (values.hasOwnProperty(key)) {
      if (Buffer.isBuffer(values[key])) {
        values[key] = values[key].toString('binary');
      }
    }
  }
```

Note now there's a discrepancy between the passed in value (a Buffer) and the result you get back from the database (a string). 

You can't pass in a string, at least, I couldn't get it to work. Creating new values failed with the error message `'[object Object]'` (that is the literal string, there is no object there) - nothing gets sent to the DB, it fails the anchor validation in waterline. Maybe I should report that as a separate error.

Duplicates #185, which was closed.

**Comment by devinivy** [comment]
Thanks for reopening!  CC @particlebanana who was previously part of the conversation.

**Comment by tjwebb** [comment]
>  but the call to _.cloneDeep(values) converts a Buffer into a weird looking object.

Yea, don't get me started on `_.cloneDeep`. I've been ripping it out of other modules where it breaks similar things. It's slow, it changes semantics between lodash versions, and it utterly wrecks perfectly good data structures, e.g Buffers, Functions, Classes (es6). If there's an opportunity to remove cloneDeep, I say we take it. 

cc @mikermcneil, who might also have some relevant thoughts, since he hasn't always agreed with me on this :)

**Comment by devinivy** [comment]
Waterline needs to wage war against its cloneDeeps!

**Comment by particlebanana** [comment]
Submitted #222 which should fix this (just removes the entire cloneDeep).
