### ISSUE TITLE
Cannot define varchar

### ISSUE THREAD

**Issue by ketysek** [balderdashy/sails-postgresql#218]
Hi, there's problem with defining varchar with this module. It completely ignores size parameter of string :-( fe.

    name: {
	type: 'string',
	size: 50
    },

Could you fix this issue in the next module update?

**Comment by aars** [comment]
This is by design. There is no advantage of `varchar` over `text` besides restricting string length.

https://github.com/balderdashy/sails-postgresql/issues/83

Postgres uses a text-field internally anyhow.
http://www.postgresql.org/docs/9.4/static/datatype-character.html

**Comment by particlebanana** [comment]
Correct. This is by design.
