### ISSUE TITLE
Case insensitive queries when using case sensitive setting

### ISSUE THREAD

**Issue by ajkitson** [balderdashy/sails-postgresql#219]
When using the [`caseSensitive` setting](https://github.com/balderdashy/sails-postgresql#configuration), is there a way to make specific queries case insensitive (ideally using the Waterline query language)? Or do you need write your own SQL and use `.query` in that case?

**Comment by particlebanana** [comment]
Right now it's one or the other. The way connections are handled in Waterline is due for some upgrades this year which should support more stateless connection handling which would allow this to be configured on a per query basis. For now writing a sql query using something like `select lower(foo) from tbl;` should do the trick.
