### ISSUE TITLE
Junction tables for many-many collections are appearing in the wrong schema

### ISSUE THREAD

**Issue by khchan** [balderdashy/sails-postgresql#227]
Example Project to replicate:
https://github.com/khchan/sails-postgres-schema-test

There are 4 models in this project: Alpha, Beta, Gamma, and Delta. Alpha and Beta have a many-many relationship with each other and have meta.schemaName set to schema1; Gamma and Delta have a many-many relationship with each other and use the default public schema.

Versions:

node@0.12.7
sails@0.12.0-rc4
sails-postgresql@0.11.1
postgresql-9.4
Lifting the project on Ubuntu 14.04.3 LTS produces expected results: alpha-beta junctionTable exists on schema1, and gamma-delta junctionTable exists on public default schema.

**However, lifting the project on CentOS 6.6 results in all the junctionTables for alpha-beta and gamma-delta to appear on the public schema.**

(I wasn't sure whether to post this in the waterline repo or here, but I figured this issue might be related to both - see [Waterline #1297)](https://github.com/balderdashy/waterline/issues/1297)

**Comment by sgress454** [comment]
@khchan Seems like you might have some old dependencies hanging around on that CentOS system.  I would wipe your `node_modules`, run `npm cache clean` and `npm install` again.

**Comment by khchan** [comment]
@sgress454 Just tried that - no luck...

**Comment by sgress454** [comment]
Hm.  Can you do `npm ls` in that app folder and confirm that the `waterline-sequel` version is 0.1.20?

**Comment by khchan** [comment]
hmm the version I get is 0.5.5

**Comment by sgress454** [comment]
Sorry--I meant `waterline-schema`.

**Comment by khchan** [comment]
Oh then yeah its 0.1.20

**Comment by sgress454** [comment]
Ok, thanks.  Can you tell me what NPM version you have installed there, then create a [gist](http://gist.github.com) of the entire output of `npm ls`?  It doesn't make much sense that you should have different outcomes if all that's different is the operating system.

**Comment by khchan** [comment]
Yeah, I'm pretty baffled by this - my npm version is 2.11.3 and here's the [gist](https://gist.github.com/khchan/9f9081d8d169a4062d9c).

**Comment by sgress454** [comment]
Could not reproduce on OS X using the same versions, and my `npm ls` was identical.  How are you starting your app on CentOS?  Is it possible that it's actually loading a different, globally installed Sails instead of the one in the `node_modules` folder?

**Comment by khchan** [comment]
Oh that was it!  Even though the global `sails -v` returned 0.12.0-rc4, uninstalling and re-installing the global sails fixed everything.  Thanks for your help!

**Comment by sgress454** [comment]
Whew!  Glad to hear it, that was shaping up to be a doozy ;)
